version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:latest-jdk17
    container_name: jenkins-server
    ports:
      - 8001:8080
      - 50000:50000
    privileged: true
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock/var/run/docker.sock